name       : utfcpp
version    : 3.2.1
release    : 3
source     :
    - https://github.com/nemtrif/utfcpp/archive/refs/tags/v3.2.1.tar.gz : 8d6aa7d77ad0abb35bb6139cb9a33597ac4c5b33da6a004ae42429b8598c9605
license    : BSL-1.0
component  : programming.library
homepage   : http://utfcpp.sourceforge.net/
summary    : UTF-8 with C++ in a Portable Way.
description: |
    UTF-8 with C++ in a Portable Way.
patterns   :
    - /* # it's a header-only library
setup      : |
    %cmake_ninja -DUTF8_SAMPLES=OFF -DUTF8_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
