name       : utfcpp
version    : '3.2'
release    : 2
source     :
    - https://github.com/nemtrif/utfcpp/archive/refs/tags/v3.2.tar.gz : cd4f9a66d23dc385bd7ea11bc0abfda8ea1ad1dcf5cd6d3a27bc551e86436364
license    : BSL-1.0
component  : programming.library
homepage   : http://utfcpp.sourceforge.net/
summary    : UTF-8 with C++ in a Portable Way.
description: |
    UTF-8 with C++ in a Portable Way.
patterns   :
    - /* # it's a header-only library
setup      : |
    %cmake_ninja -DUTF8_SAMPLES=OFF -DUTF8_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
